theme: jekyll-theme-minimal
title: <p align="center"> Ananya Swaminathan </p>
logo: "/files/Grad_Photo_Circ.png?raw=true"
description: Hello! I am currently a BS/MS student in the Johns Hopkins Department of Biomedical Engineering. 
