theme: jekyll-theme-minimal
title: <p align="center"> Ananya Swaminathan </p>
logo: "/files/Grad_Photo_Circ.png?raw=true"
description: <p align="left"> Hello! I am currently a BS/MSE student in the Johns Hopkins Department of Biomedical Engineering. </p>
<img src="https://github.com/ananyas713/ananyas713.github.io/blob/master/files/Linkedin-logo.png" 
     width="100" 
     height="100" />
