title: <p align="center"> Ananya Swaminathan </p>
logo: "/files/Grad_Photo_Circ.png?raw=true"
description: 
     <p align="center">
     <a href="https://www.linkedin.com/in/ananyas713/"><img src="/files/Linkedin-logo.png" 
          width="50" 
          height="50" /></a>
     <a href="https://www.github.com/ananyas713/"><img src="/files/Github-logo.png" 
          width="50" 
          height="50" /></a>
     </p>
     
     <p align="left"> 
     Hello! I am currently a BS/MSE student in the Johns Hopkins Department of Biomedical Engineering. 
     </p>

theme: jekyll-theme-minimal
